version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: monday
    versioning-strategy: widen
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    labels:
      - dependencies
    commit-message:
      prefix: composer
    groups:
      composer-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
